#!/usr/bin/env bash

echo "Setting up ctags"

(ctags --version 2>/dev/null || echo "none") | grep -i exuberant

if [[ $? == 1 ]]; then

    echo "Installing ctags"

    platform='unknown'
    unamestr=$(uname)
    if [[ "$unamestr" == 'Darwin' ]]; then
        if hash brew 1>&2>/dev/null; then
            brew install ctags
        elif hash port 1>&2>/dev/null; then
            port install ctags
        else
            echo "ERROR: I don't know what package manager you're using!"
            exit 1
        fi
    elif [[ "$unamestr" == 'Linux' ]]; then
        if hash apt-get 1>&2>/dev/null; then
            sudo apt-get -y install exuberant-ctags
        elif hash yum 1>&2>/dev/null; then
            sudo yum -y install ctags
        else
            echo "ERROR: I don't know what package manager you're using!"
            exit 1
        fi
    else
        echo "ERROR: I don't support installation for this OS yet!"
        exit 1
    fi

fi


dotfiles_repo=$(utils/repo_path)
source_path=$dotfiles_repo/ctags/dotctags
symlink_path=$HOME/.ctags
backup_path=$HOME/.ctags.old

if ! [ "$(readlink $symlink_path)" = "$source_path" ]; then

    if [ -e $symlink_path ]; then
        echo "Moving current $symlink_path to $backup_path"
        mv $symlink_path $backup_path
    fi

    echo "Symlinking $symlink_path to $source_path"
    ln -s $source_path $symlink_path
else
    echo "$symlink_path points correctly to $source_path"
fi
