#!/usr/bin/env bash

echo "Setting up vim dotfile and plugins"

dotfiles_repo=$(utils/repo_path)
echo "Dotfiles repo is in $dotfiles_repo"

ensure_symlink () {
    symlink_path=$1
    target_path=$2
    backup_path=${symlink_path}.old

    if ! [ "$(readlink $symlink_path)" = "$target_path" ]; then

        if [ -e $symlink_path ]; then
            echo "Moving current $symlink_path to $backup_path"
            mv $symlink_path $backup_path
        fi

        echo "Symlinking $symlink_path to $target_path"
        ln -s $target_path $symlink_path
    else
        echo "$symlink_path points correctly to $target_path"
    fi
}

ensure_symlink $HOME/.vimrc $dotfiles_repo/vim/vimrc

echo "Ensuring vim plugins and docs"

dotvim_path=$dotfiles_repo/vim/dotvim
mkdir -p $dotvim_path
ensure_symlink $HOME/.vim $dotvim_path

bundle_path=$dotvim_path/bundle

ensure_symlink $dotvim_path/autoload $dotfiles_repo/vim/autoload


ensure_plugin () {
    plugin_name=$1
    repo_url=$2
    plugin_path=$bundle_path/$plugin_name

    if ! [ -d $plugin_path ]; then
        echo "Installing plugin: $plugin_name"
        git clone $repo_url $plugin_path
    else
        echo "Plugin $plugin_name is already installed at $plugin_path"
    fi
}


# ctrlp plugin
ensure_plugin ctrlp.vim https://github.com/kien/ctrlp.vim.git

# NERDTree plugin
ensure_plugin nerdtree https://github.com/scrooloose/nerdtree.git

# syntastic plugin
ensure_plugin syntastic https://github.com/relaxdiego/syntastic

pip list | grep flake8 > /dev/null

if [ $? == 1 ]; then
    echo "Installing flake8"
    pip install flake8
fi

# Ag plugin
ensure_plugin ag.vim https://github.com/rking/ag.vim

# test.vim plugin; supersedes vim-rspec
ensure_plugin test.vim https://github.com/relaxdiego/vim-test

# surround plugin
ensure_plugin vim-surround https://github.com/tpope/vim-surround

# vim-repeat plugin
ensure_plugin vim-repeat https://github.com/relaxdiego/vim-repeat

# tagbar plugin
ensure_plugin tagbar https://github.com/majutsushi/tagbar

# colorschemes plugin
ensure_plugin vim-colorschemes https://github.com/relaxdiego/vim-colorschemes

# lightline plugin
ensure_plugin lightline.vim https://github.com/relaxdiego/lightline.vim

# vim-endwise plugin
ensure_plugin vim-endwise https://github.com/relaxdiego/vim-endwise

# tslime.vim plugin
ensure_plugin tslime.vim https://github.com/relaxdiego/tslime.vim

# Tcomment plugin
ensure_plugin tcomment.vim https://github.com/relaxdiego/tcomment_vim

# ultisnips and friends
ensure_plugin ultisnips https://github.com/relaxdiego/ultisnips
ensure_plugin vim-snippets https://github.com/relaxdiego/vim-snippets
ensure_symlink $dotvim_path/UltiSnips $dotvim_path/bundle/vim-snippets/UltiSnips
ensure_symlink $dotvim_path/MyUltiSnips $dotfiles_repo/vim/MyUltiSnips

# autopairs plugin
ensure_plugin auto-pairs https://github.com/relaxdiego/auto-pairs

# vim-go plugin
ensure_plugin vim-go https://github.com/relaxdiego/vim-go
echo "Installing go binaries"
vim +GoInstallBinaries +q

# ansible-vim plugin
ensure_plugin ansible-vim https://github.com/relaxdiego/ansible-vim

# YouCompleteMe plugin
plugin_name='YouCompleteMe'
ensure_plugin $plugin_name https://github.com/relaxdiego/YouCompleteMe
if ! [ -f $bundle_path/$plugin_name/third_party/ycmd/ycm_core.so ]; then
    cd $bundle_path/$plugin_name
    git submodule update --init --recursive
    ./install.py --clang-completer --gocode-completer
    cd -
else
    echo "Plugin YouCompleteMe is already configured"
fi
echo "If you're having problems with YCM, see https://github.com/Valloric/YouCompleteMe/issues/8#issuecomment-34374807"

# Generate the docs for all plugins
echo "Running 'Helptags' command"
vim +Helptags +q

# Add puppet syntax highlighting
if ! [ -f ${dotvim_path}/syntax/puppet.vim ]; then
    echo "Adding puppet syntax highlighting and goodies"
    tmp_puppetvims=/tmp/puppetvims
    mkdir -p $tmp_puppetvims
    cd $tmp_puppetvims
    git init
    git remote add -f origin https://github.com/puppetlabs/puppet
    git config core.sparseCheckout true
    echo "ext/vim/" >> .git/info/sparse-checkout
    git pull origin master
    cp -r ext/vim/* $dotvim_path
    cd -
else
    echo "Puppet syntax highlighting and goodies already exist"
fi

# Add python indentation script
if ! [ -f ${dotvim_path}/indent/python.vim ]; then
    echo "Adding python indentation script"
    wget -O $dotvim_path/indent/python.vim http://www.vim.org/scripts/download_script.php?src_id=4316
else
    echo "Python indentation script already exist"
fi
