set nocompatible
filetype plugin on
syntax on
filetype plugin indent on

let g:netrw_liststyle=3
execute pathogen#infect()

" Set indentation preferences
"   ts  = 'number of spaces that <Tab> in file uses'
"   sts = 'number of spaces that <Tab> uses while editing'
"   sw  = 'number of spaces to use for (auto)indent step'
" for details see: vimdoc.sourceforge.net/htmldoc/quickref.html#option-list
set expandtab
autocmd Filetype html setlocal ts=2 sts=2 sw=2
autocmd Filetype ruby setlocal ts=2 sts=2 sw=2
autocmd Filetype python setlocal ts=4 sts=4 sw=4

" Show column rulers
set colorcolumn=72,80
highlight ColorColumn ctermbg=darkgray guibg=darkgray


" Show whitespace
set list
set listchars=eol:¬,tab:>>,trail:.,extends:>,precedes:<

" NERDTree settings
map <C-n> :NERDTreeToggle<CR>
let NERDTreeIgnore = ['\.pyc$']

" Show line numbers
set number

" Remove trailing whitespace for certain filetypes
fun! <SID>StripTrailingWhitespaces()
    let l = line(".")
    let c = col(".")
    %s/\s\+$//e
    call cursor(l, c)
endfun

autocmd FileType c,cpp,java,php,ruby,python,vim autocmd BufWritePre
        \ <buffer> :call <SID>StripTrailingWhitespaces()

" Disable arrow keys
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>

" Setting for ctrlp plugin
set runtimepath^=~/.vim/bundle/ctrlp.vim
let g:ctrlp_map = '<c-p>'
let g:ctrlp_max_files = 0
let g:ctrlp_max_depth = 40
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_working_path_mode = ''
set wildignore+=*/tmp/*,*.so,*.swp,*.zip     " MacOSX/Linux
set wildignore+=*\\tmp\\*,*.swp,*.zip,*.exe  " Windows

let g:ctrlp_custom_ignore = {
  \ 'dir':  '\v[\/]\.(git|hg|svn)$',
  \ 'coverage':  '\v(htmlcov|\.?coverage)$',
  \ 'file': '\v\.(exe|so|dll)$',
  \ }
