git:
  log:
    showGraph: always
  autoFetch: false
  fetchInterval: 0
  paging:
    colorArg: always
    pager: delta --paging=never
gui:
  nerdFontsVersion: "3"
refresher:
  refreshInterval: 10
  fetchInterval: 0
keybinding:
  files:
    findBaseCommitForFixup: <disabled>  # Use <c-f> to page down
  universal:
    nextPage: <c-f>
    prevPage: <c-b>
    gotoTop: g
    gotoBottom: G
customCommands:
  - key: "u"
    command: |
      git undo
    description: "undo the last commit"
    context: files
  - key: "c"
    command: |
      GIT_EDITOR='~/bin/nvim -c "normal gg" -c "startinsert!"' git commit --edit  --template <(echo "{{ .Form.Type }}{{if .Form.Scopes}}({{ .Form.Scopes }}){{end}}{{if eq .Form.Breaking `yes`}}!{{end}}: ")
    description: "commit staged changes"
    context: files
    subprocess: true
    prompts:
      - type: "menu"
        title: "Type of commit?"
        key: "Type"
        options:
          - name: "Feature"
            description: "A new feature"
            value: "feat"
          - name: "Fix"
            description: "A bug fix"
            value: "fix"
          - name: "Chores"
            description: "Other changes that don't modify src or test files"
            value: "chore"
          - name: "Code Refactoring"
            description: "A code change that neither fixes a bug nor adds a feature"
            value: "refactor"
          - name: "Documentation"
            description: "Documentation only changes"
            value: "docs"
          - name: "Styles"
            description: "Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)"
            value: "style"
          - name: "Tests"
            description: "Adding missing tests or correcting existing tests"
            value: "test"
          - name: "Builds"
            description: "Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, npm)"
            value: "build"
          - name: "Continuous Integration"
            description: "Changes to our CI configuration files and scripts (example scopes: Travis, Circle, BrowserStack, SauceLabs)"
            value: "ci"
          - name: "Reverts"
            description: "Reverts a previous commit"
            value: "revert"
          - name: "Performance Improvements"
            description: "A code change that improves performance"
            value: "perf"
      - type: "input"
        title: "Scope of change?"
        key: "Scopes"
      - type: "menu"
        title: "Has breaking change?"
        key: "Breaking"
        options:
          - name: "Does not break any public API"
            value: "no"
          - name: "Breaks its public API"
            value: "yes"
