#!/usr/bin/env bash
healthy=true

check_dep () {
    dep=$1
    depname=${2:-$1}

    if ! hash $dep 2>/dev/null; then
        echo "MISSING: $depname"
        healthy=false
    fi
}

check_dep python
check_dep pip
check_dep ruby
check_dep gem rubygems
check_dep go

if [ "$healthy" = false ]; then
    echo "Please fix the missing dependencies and try again"
    exit 1
else
    echo "All dependencies met"
    exit 0
fi
