#!/usr/bin/env bash
set -ex

GO_VERSION=1.22.3
GOLANGCI_LINT_VERSION=1.55.2
GOFUMPT_VERSION="636d7a7b9ae6db4704a12cd990b57a7c8f0ede78" # v0.6.0

if asdf list golang "$GO_VERSION" | grep "$GO_VERSION"; then
    echo "Go is already installed"
else
    echo "Installing Go ${GO_VERSION} using asdf"
    asdf plugin-add golang https://github.com/kennyp/asdf-golang.git || true
    asdf install golang "${GO_VERSION}"
fi
asdf global golang "${GO_VERSION}"

if asdf list golangci-lint "$GOLANGCI_LINT_VERSION" | grep "$GOLANGCI_LINT_VERSION"; then
    echo "golangci-lint is already installed"
else
    echo "Installing golangci-lint ${GOLANGCI_LINT_VERSION} using asdf"
    asdf plugin add golangci-lint https://github.com/hypnoglow/asdf-golangci-lint.git || true
    asdf install golangci-lint "${GOLANGCI_LINT_VERSION}"
fi
asdf global golangci-lint "${GOLANGCI_LINT_VERSION}"

echo "Installing https://github.com/mvdan/goimports latest"
go install golang.org/x/tools/cmd/goimports@latest

echo "Installing https://github.com/mvdan/gofumpt ${GOFUMPT_VERSION}"
go install mvdan.cc/gofumpt@"${GOFUMPT_VERSION}"
