#!/usr/bin/env bash
set -ex

GO_VERSION=1.19.8
GOLANGCI_LINT_VERSION=1.52.2

if go &>/dev/null; then
    echo "Go is already installed"
else
    echo "Installing Go ${GO_VERSION} using asdf"
    asdf plugin-add golang https://github.com/kennyp/asdf-golang.git
    asdf install golang "${GO_VERSION}"
fi
asdf global golang "${GO_VERSION}"

if golangci-lint &>/dev/null; then
    echo "golangci-lint is already installed"
else
    echo "Installing golangci-lint ${GOLANGCI_LINT_VERSION} using asdf"
    asdf install golangci-lint "${GOLANGCI_LINT_VERSION}"
fi
asdf global golangci-lint "${GOLANGCI_LINT_VERSION}"

# Install the Go plugin for vim
source $HOME/.local/dotfiles.relaxdiego.com/vim_plugin_lib
ensure_plugin 'vim-go' https://github.com/fatih/vim-go.git v1.26

# Ensure Go support for YCM
echo "--go-completer" > $HOME/.local/dotfiles.relaxdiego.com/ycm_installer_flags/golang

# Re-install YouCompleteMe now with go support
# For more help on Go completion, see https://github.com/ycm-core/YouCompleteMe#explanation-for-the-quick-start-1
rm -rf $bundle_path/YouCompleteMe
$HOME/.local/dotfiles.relaxdiego.com/install-YouCompleteMe
