#!/usr/bin/env bash
set -e

export dotvim_path=~/.vim
export bundle_path=$dotvim_path/bundle

ensure_plugin () {
    plugin_name=$1
    repo_url=$2
    git_ref=${3:-}
    plugin_path=$bundle_path/$plugin_name

    if ! [ -d "$plugin_path" ]; then
        echo "Installing plugin: $plugin_name"
        git clone "$repo_url" "$plugin_path"
    else
        echo "Plugin $plugin_name is already installed at $plugin_path"
    fi

    if [ -n "$git_ref" ]; then
        echo "Checking out $plugin_name at $git_ref"
        cd "$plugin_path"
        git fetch --all
        git checkout "$git_ref"
    fi
}
